method: "bayes"
name: "MUSE-SWEEP"
metric:
  name: "accuracy"
  goal: "maximize"
parameters:
  lr:
    min: 0.00005
    max: 0.01
  batch_size:
    values: [16, 32, 64]
  dropout_prob:
    min: 0.1
    max: 0.5
  D_h:
    values: [256, 512, 768]
  lambda_orthogonality:
    min: 0.00005
    max: 0.003
  M_t:
    values: [8, 16, 32]
  alpha:
    min: 0.1
    max: 0.9
