method: bayes
metric:
  goal: maximize
  name: accuracy
parameters:
  D_h:
    values:
      - 256
      - 512
      - 768
      - 1024
      - 1280
      - 1536
  M_t:
    distribution: int_uniform
    min: 4
    max: 14
  alpha:
    distribution: uniform
    max: 0.9
    min: 0.1
  dropout_prob:
    distribution: uniform
    max: 0.5
    min: 0.1
  lambda_orthogonality:
    distribution: uniform
    max: 0.003
    min: 5e-05
  lr:
    distribution: uniform
    max: 0.01
    min: 5e-05
program: src/sweep.py
