method: bayes
metric:
  goal: maximize
  name: accuracy
parameters:
  D_h:
    values:
      - 256
      - 512
      - 768
      - 1024
      - 1280
      - 1536
      - 2056
  alpha:
    distribution: uniform
    max: 0.6
    min: 0.1
  batch_size:
    values:
      - 8
      - 16
      - 32
  dropout_prob:
    distribution: uniform
    max: 0.9
    min: 0.1
  lambda_orthogonality:
    distribution: uniform
    max: 0.01
    min: 0.0001
  lr:
    distribution: uniform
    max: 0.0005
    min: 0.000005
program: src/sweep.py
